### ISSUE TITLE
Using same variable multiples times in operation makes provenance tree layout fail

### ISSUE THREAD

**Issue by remram44** [VisTrails/DAT#19]
```
Traceback (most recent call last):
  File "dat/gui/data_provenance.py", line 259, in showVariable
    layout.addToScene(self._scene, sink=variable)
  File "dat/gui/data_provenance.py", line 157, in addToScene
    nodes = rows[row]
KeyError: 1
```

**Comment by remram44** [comment]
Somewhat fixed by 1272b630.
